# Generated by Django 6.1 on 2026-09-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('UNPAID', 'Unpaid / Credit')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
