# Generated by Django 6.1 on 2026-09-07 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_salesorder_amount_paid_salesorder_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session_id', 'product'), name='unique_cart_product_per_session')],
            },
        ),
    ]
